{% set name = "TileDB" %}
{% set version = "1.4.0" %}
{% set sha256 = "a5397beba0a6e4e26e5cbc0f4993a4ea2ac82fea17d28e3b1a2b4609f89a7f78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - pkg-config  # [not win]
  host:
    - aws-sdk-cpp 1.4.*
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - blosc 1.*
    - tbb-devel 2018.0.5
  run:
    - aws-sdk-cpp 1.4.*
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - blosc 1.*
    - tbb 2018.0.5

test:
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [unix]
    - test -e $PREFIX/include/tiledb/tiledb  # [unix]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB sparse and dense multi-dimensional array data management'
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - jakebolewski
    - tdenniston
