{% set name = "TileDB" %}
{% set version = "2.27.1" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9433475cabd1af6384d3c6b8ec0310169997a2e323ebe236a83ac3e709e72cc5

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', max_pin='x.x') }}
  error_overdepending: true
  error_overlinking: true

requirements:
  build:
    - make  # [unix]
    - cmake !=3.29.1
    - ninja  # [win]
    - pkg-config  # [not win]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - file  # [arm64]
    - zip  # [not win]
    - unzip  # [not win]
    - curl  # [not win]
    - tar  # [not win]
    # These are declared as vcpkg dependencies by TileDB but are not actually used.
    - libxml2  # [not win]
    - capnproto
  host:
    - aws-c-auth  # [linux64]
    - aws-c-cal  # [linux64]
    - aws-c-common  # [linux64]
    - aws-c-compression  # [linux64]
    - aws-c-event-stream  # [linux64]
    - aws-c-http  # [linux64]
    - aws-c-io  # [linux64]
    - aws-c-mqtt  # [linux64]
    - aws-c-s3  # [linux64]
    - aws-c-sdkutils  # [linux64]
    - aws-checksums  # [linux64]
    - aws-sdk-cpp
    - aws-crt-cpp
    - azure-core-cpp
    - azure-identity-cpp
    - azure-storage-common-cpp
    - azure-storage-blobs-cpp
    - bzip2
    - capnproto
    - fmt
    - libabseil
    - libgoogle-cloud-devel
    - libgoogle-cloud-storage-devel
    - libcurl
    - libwebp-base
    - lz4-c
    - openssl
    - s2n  # [linux64]
    - spdlog
    - zlib
    - zstd
    # see: https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/108,
    - libcrc32c  # [linux64 or win]
test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  #  downstreams:
  #  - tiledb-py
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [not win]
    - test -e $PREFIX/include/tiledb/tiledb  # [not win]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [not win]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\\tiledb.dll (exit 0) else (exit 1)  # [win]

    # libcurl must be installed at runtime
    - test -e $PREFIX/lib/libcurl$SHLIB_EXT  # [not win]
    - if exist %LIBRARY_LIB%\\libcurl.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\\libcurl.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - teo-tsirpanis
    - jdblischak
    - akrherz
    - shelnutt2
    - ihnorton
    - nguyenv
    - xylar
