{% set name = "TileDB" %}
{% set version = "2.3.3" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ca65e01788e7149bcdef9aeab9b1449169da3e538eec6200064b06603747db1b

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', 'x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - make  # [unix]
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - curl  # [arm64]
  run:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - curl  # [arm64]


test:
  #  downstreams:
  #  - tiledb-py
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [not win]
    - test -e $PREFIX/include/tiledb/tiledb  # [not win]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [not win]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\tiledb.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - shelnutt2
    - ihnorton
    - nguyenv
