{% set version = "1.3.0" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB/archive/{{ version }}.tar.gz
  sha256: 9ca8d472ba2ad86c10d2a9565a4e27db51a97b3a52e45e36d1f7bcd9b4e85229

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake >=3.2
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - aws-sdk-cpp 1.4.*
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - blosc 1.*
  run:
    - aws-sdk-cpp 1.4.*
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - blosc 1.*

test:
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [unix]
    - test -e $PREFIX/include/tiledb/tiledb  # [unix]
    - test -e $PREFIX/lib/libtiledb.a  # [unix]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB sparse and dense multi-dimensional array data management'
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - jakebolewski
    - tdenniston
