{% set name = "TileDB" %}
{% set version = "2.12.0" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 212e80769199c13956e1eb31b56a510fb46ee56310234481a6aaf4a07acf2efb

build:
  number: 1
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - make  # [unix]
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('cxx') }}
    - file  # [arm64]
  host:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - openssl
    - curl
  run:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - openssl
    - curl


test:
  #  downstreams:
  #  - tiledb-py
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [not win]
    - test -e $PREFIX/include/tiledb/tiledb  # [not win]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [not win]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\tiledb.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - akrherz
    - stavrospapadopoulos
    - shelnutt2
    - ihnorton
    - nguyenv
