{% set version = "1.6.2" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB/archive/{{ version }}.tar.gz
  sha256: 001e49f4a9408f0e9064628ddcde201a5f76cf7a87c5bb17799c45e648001393

build:
  number: 3
  run_exports:
    # no ABI info but the so breaks in minor releases
    - {{ pin_subpackage('tiledb') }}
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - tbb-devel 2018.0.5
  run:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - tbb 2018.0.5
    - curl

test:
  #  downstreams:
  #  - tiledb-py
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [not win]
    - test -e $PREFIX/include/tiledb/tiledb  # [not win]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [linux]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [osx]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\tiledb.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB sparse and dense multi-dimensional array data management'
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - jakebolewski
    - tdenniston
    - ihnorton
