appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Yg5KRxYrvoeXnRSaJLwHIA0dN3mWWDki01N1AIi5wIG+EmVohaiTkK4fVQXuKFrdKu0WrAn6DYMMMj/Mo37bBw9GFWLngpfO+hq35yXN32YuptxAOixPbwJo/HiejhxUc1Y6RMOA0so5U7Nm8zOlGXYONmBcKUdjc2gWaHKH3fd8856YrYx65qpM8LwJb82ruoWCJgPd9QLhRRfpiTniwP7ghdOPgUeOd1gOHzpSaWtYGU9Fp6OkPSrTlJJFeNFlgtv7apeftlxLqXQW42Nwxtn/Dmwet1idThxNCEWSxLHuQlEUTVxK8H7373IUFcQyeAMJGYaM6WJSDcq1uSnXeUp2vnbS30ExCxD1OTkUdMmPMxaAQN18f+MsfJP3XAKTF4Qumy3Ttk95CjZQhbshXs98vVgbXlJomqFQIjGn3Sbop72JvwcBe9nic6BFCCIfz5XlmFumQnqgDns+rVGeF9Lqmte11FFEhk/iDvhKXL7PrJ4gS9Zv60SMKiQkwlU4Ph1MQPri/YrH/aZDGY6M0CK+sFde804ueVWUW7Px706QTl1jeIMlfC5jt40fUZX85c+InrvW033us6GEkH/qEZ9meyZpto/4iqrvOcDRa0zhiNoblgSzdTMThBGLtgKFl8tMc8pgl5Tp740AzXhNCHSgox8TLc9ryGNhpxTxmug=}
provider:
  win: azure
conda_forge_output_validation: false
