set(VCPKG_TARGET_ARCHITECTURE ppc64le)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

# Use the compilers set by Conda.
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_C_COMPILER=$ENV{CC};-DCMAKE_CXX_COMPILER=$ENV{CXX}")

set(VCPKG_BUILD_TYPE release)
